#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: access-tokens-add <token-path>"
    exit 1
fi

if [ -e "$1" ]; then
    echo Token path already exists: $1
    exit 1
fi

# make sure token parent dir exists
token_dir=$(dirname "$1")
if [ ! -d "$token_dir" ]; then 
    mkdir -p $token_dir
    echo Created empty directory: $token_dir
fi
unset token_dir

# add token
read -s -p "Enter access token value: " token_value
echo
echo $token_value | openssl aes-256-cbc -a -salt > $1
unset token_value
